/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.heptagon.thirema.dataprocessor.kafka.gateway.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class AvroDeviceData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2643967105214980464L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroDeviceData\",\"namespace\":\"com.heptagon.thirema.dataprocessor.kafka.gateway.avro\",\"fields\":[{\"name\":\"ipAddress\",\"type\":\"string\"},{\"name\":\"measures\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroMeasureData\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroDeviceData> ENCODER =
      new BinaryMessageEncoder<AvroDeviceData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroDeviceData> DECODER =
      new BinaryMessageDecoder<AvroDeviceData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroDeviceData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroDeviceData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroDeviceData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroDeviceData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroDeviceData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroDeviceData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroDeviceData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroDeviceData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence ipAddress;
  @Deprecated public java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> measures;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroDeviceData() {}

  /**
   * All-args constructor.
   * @param ipAddress The new value for ipAddress
   * @param measures The new value for measures
   */
  public AvroDeviceData(CharSequence ipAddress, java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> measures) {
    this.ipAddress = ipAddress;
    this.measures = measures;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return ipAddress;
    case 1: return measures;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: ipAddress = (CharSequence)value$; break;
    case 1: measures = (java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public CharSequence getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(CharSequence value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'measures' field.
   * @return The value of the 'measures' field.
   */
  public java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> getMeasures() {
    return measures;
  }


  /**
   * Sets the value of the 'measures' field.
   * @param value the value to set.
   */
  public void setMeasures(java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> value) {
    this.measures = value;
  }

  /**
   * Creates a new AvroDeviceData RecordBuilder.
   * @return A new AvroDeviceData RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new AvroDeviceData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroDeviceData RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new AvroDeviceData RecordBuilder by copying an existing AvroDeviceData instance.
   * @param other The existing instance to copy.
   * @return A new AvroDeviceData RecordBuilder
   */
  public static Builder newBuilder(AvroDeviceData other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroDeviceData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroDeviceData>
    implements org.apache.avro.data.RecordBuilder<AvroDeviceData> {

    private CharSequence ipAddress;
    private java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> measures;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[0].schema(), other.ipAddress);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.measures)) {
        this.measures = data().deepCopy(fields()[1].schema(), other.measures);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroDeviceData instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroDeviceData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[0].schema(), other.ipAddress);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.measures)) {
        this.measures = data().deepCopy(fields()[1].schema(), other.measures);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public CharSequence getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public Builder setIpAddress(CharSequence value) {
      validate(fields()[0], value);
      this.ipAddress = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'measures' field.
      * @return The value.
      */
    public java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> getMeasures() {
      return measures;
    }


    /**
      * Sets the value of the 'measures' field.
      * @param value The value of 'measures'.
      * @return This builder.
      */
    public Builder setMeasures(java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> value) {
      validate(fields()[1], value);
      this.measures = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'measures' field has been set.
      * @return True if the 'measures' field has been set, false otherwise.
      */
    public boolean hasMeasures() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'measures' field.
      * @return This builder.
      */
    public Builder clearMeasures() {
      measures = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroDeviceData build() {
      try {
        AvroDeviceData record = new AvroDeviceData();
        record.ipAddress = fieldSetFlags()[0] ? this.ipAddress : (CharSequence) defaultValue(fields()[0]);
        record.measures = fieldSetFlags()[1] ? this.measures : (java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroDeviceData>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroDeviceData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroDeviceData>
    READER$ = (org.apache.avro.io.DatumReader<AvroDeviceData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ipAddress);

    long size0 = this.measures.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData e0: this.measures) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ipAddress = in.readString(this.ipAddress instanceof Utf8 ? (Utf8)this.ipAddress : null);

      long size0 = in.readArrayStart();
      java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> a0 = this.measures;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData>((int)size0, SCHEMA$.getField("measures").schema());
        this.measures = a0;
      } else a0.clear();
      SpecificData.Array<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ipAddress = in.readString(this.ipAddress instanceof Utf8 ? (Utf8)this.ipAddress : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> a0 = this.measures;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData>((int)size0, SCHEMA$.getField("measures").schema());
            this.measures = a0;
          } else a0.clear();
          SpecificData.Array<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureData();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










