/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.heptagon.thirema.dataprocessor.kafka.gateway.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class AvroMeasureConfig extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6378942483112143075L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroMeasureConfig\",\"namespace\":\"com.heptagon.thirema.dataprocessor.kafka.gateway.avro\",\"fields\":[{\"name\":\"ipAddress\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"enabled\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroMeasureConfig> ENCODER =
      new BinaryMessageEncoder<AvroMeasureConfig>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroMeasureConfig> DECODER =
      new BinaryMessageDecoder<AvroMeasureConfig>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroMeasureConfig> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroMeasureConfig> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroMeasureConfig> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroMeasureConfig>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroMeasureConfig to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroMeasureConfig from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroMeasureConfig instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroMeasureConfig fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence ipAddress;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public boolean enabled;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroMeasureConfig() {}

  /**
   * All-args constructor.
   * @param ipAddress The new value for ipAddress
   * @param name The new value for name
   * @param enabled The new value for enabled
   */
  public AvroMeasureConfig(java.lang.CharSequence ipAddress, java.lang.CharSequence name, java.lang.Boolean enabled) {
    this.ipAddress = ipAddress;
    this.name = name;
    this.enabled = enabled;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ipAddress;
    case 1: return name;
    case 2: return enabled;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ipAddress = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: enabled = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public java.lang.CharSequence getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.CharSequence value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'enabled' field.
   * @return The value of the 'enabled' field.
   */
  public boolean getEnabled() {
    return enabled;
  }


  /**
   * Sets the value of the 'enabled' field.
   * @param value the value to set.
   */
  public void setEnabled(boolean value) {
    this.enabled = value;
  }

  /**
   * Creates a new AvroMeasureConfig RecordBuilder.
   * @return A new AvroMeasureConfig RecordBuilder
   */
  public static com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder newBuilder() {
    return new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder();
  }

  /**
   * Creates a new AvroMeasureConfig RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroMeasureConfig RecordBuilder
   */
  public static com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder newBuilder(com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder other) {
    if (other == null) {
      return new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder();
    } else {
      return new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder(other);
    }
  }

  /**
   * Creates a new AvroMeasureConfig RecordBuilder by copying an existing AvroMeasureConfig instance.
   * @param other The existing instance to copy.
   * @return A new AvroMeasureConfig RecordBuilder
   */
  public static com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder newBuilder(com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig other) {
    if (other == null) {
      return new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder();
    } else {
      return new com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroMeasureConfig instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroMeasureConfig>
    implements org.apache.avro.data.RecordBuilder<AvroMeasureConfig> {

    private java.lang.CharSequence ipAddress;
    private java.lang.CharSequence name;
    private boolean enabled;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[0].schema(), other.ipAddress);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.enabled)) {
        this.enabled = data().deepCopy(fields()[2].schema(), other.enabled);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroMeasureConfig instance
     * @param other The existing instance to copy.
     */
    private Builder(com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[0].schema(), other.ipAddress);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enabled)) {
        this.enabled = data().deepCopy(fields()[2].schema(), other.enabled);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder setIpAddress(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ipAddress = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'enabled' field.
      * @return The value.
      */
    public boolean getEnabled() {
      return enabled;
    }


    /**
      * Sets the value of the 'enabled' field.
      * @param value The value of 'enabled'.
      * @return This builder.
      */
    public com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder setEnabled(boolean value) {
      validate(fields()[2], value);
      this.enabled = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'enabled' field has been set.
      * @return True if the 'enabled' field has been set, false otherwise.
      */
    public boolean hasEnabled() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'enabled' field.
      * @return This builder.
      */
    public com.heptagon.thirema.dataprocessor.kafka.gateway.avro.AvroMeasureConfig.Builder clearEnabled() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroMeasureConfig build() {
      try {
        AvroMeasureConfig record = new AvroMeasureConfig();
        record.ipAddress = fieldSetFlags()[0] ? this.ipAddress : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.enabled = fieldSetFlags()[2] ? this.enabled : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroMeasureConfig>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroMeasureConfig>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroMeasureConfig>
    READER$ = (org.apache.avro.io.DatumReader<AvroMeasureConfig>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ipAddress);

    out.writeString(this.name);

    out.writeBoolean(this.enabled);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ipAddress = in.readString(this.ipAddress instanceof Utf8 ? (Utf8)this.ipAddress : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.enabled = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ipAddress = in.readString(this.ipAddress instanceof Utf8 ? (Utf8)this.ipAddress : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.enabled = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










